-- MySQL Script generated by MySQL Workbench
-- Fri May 11 12:00:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flisol2018
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flisol2018
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flisol2018` DEFAULT CHARACTER SET utf8 ;
USE `flisol2018` ;

-- -----------------------------------------------------
-- Table `flisol2018`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flisol2018`.`fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NULL,
  `endereco` VARCHAR(120) NULL,
  `cidade` VARCHAR(60) NULL,
  `estado` VARCHAR(2) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(120) NULL,
  `cnpj` VARCHAR(18) NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flisol2018`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flisol2018`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NULL,
  `preco` FLOAT NULL,
  `descricao` TEXT NULL,
  `estoque` INT NULL,
  `fornecedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_fornecedores_idx` (`fornecedores_id` ASC),
  CONSTRAINT `fk_produtos_fornecedores`
    FOREIGN KEY (`fornecedores_id`)
    REFERENCES `flisol2018`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flisol2018`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flisol2018`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NULL,
  `cpf` VARCHAR(14) NULL,
  `endereco` VARCHAR(120) NULL,
  `cidade` VARCHAR(60) NULL,
  `estado` VARCHAR(2) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(120) NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flisol2018`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flisol2018`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `clientes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_clientes1_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `flisol2018`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flisol2018`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flisol2018`.`itens_venda` (
  `vendas_id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  INDEX `fk_itens_venda_vendas1_idx` (`vendas_id` ASC),
  INDEX `fk_itens_venda_produtos1_idx` (`produtos_id` ASC),
  CONSTRAINT `fk_itens_venda_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `flisol2018`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_venda_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `flisol2018`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
